# General
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="garyblessington"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Path: homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/Library/Python/3.8/bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="/opt/homebrew/var/nodebrew/current/bin:$PATH"
export NODEBREW_ROOT="/opt/homebrew/var/nodebrew"

# エイリアス
alias vim="nvim"
alias ls="eza"
alias ll="eza --icons -l"
alias tree="eza --icons -T"
alias hp="peco_select_history"
alias cdp="cd_by_peco_on_current_dir"
alias cdpr="cd_by_peco_on_root_dir"
alias vimp="vim_by_peco_on_current_dir"
alias vimpr="vim_by_peco_on_root_dir"
alias cdr='cd ~/Repos'
alias gp='git pull'
alias gmp='git switch main && gp'
alias gsp='git switch stg && gp'
alias gc='git switch -c'
alias gs='git switch'
alias shell='open -a Ghostty .'
alias codex='open -a Codex .'


# ============
# __ ファイルの検索
# ------------
function _ffile() {
  fd --type f "$1" . \
    | fzf --preview 'bat --color=always {} 2>/dev/null || sed -n "1,200p" {}'
}

# ============
# 現在のdir配下からfzfでファイル名を検索し、対象をvimで開く
# ------------
function vimf() {
  local file=$(_ffile "$1") || return
  vim "$file"
}

# ============
# 現在のdir配下からfzfでファイル名を検索し、対象をvimで開く
# ------------
function codef() {
  local file=$(_ffile "$1") || return
  code "$file"
}


# ============
# ~/Repos/ 配下のリポジトリをfzfで検索して移動する
# ------------
function cdr() {
  local repo
  repo=$(
    fd -H -t d '^\.git$' ~/Repos --max-depth 3 |
      sed -e 's#/.git/$##' -e "s#^$HOME/Repos/##" |
      fzf --height=40% --reverse
  )
  [[ -n "$repo" ]] && cd "$HOME/Repos/$repo"
}

# ============
# __ ファイル検索用
# ------------
function _fsearch() {
  rg --line-number --no-heading --color=always "$1" . \
    | fzf --ansi \
          --delimiter=: \
          --preview 'bat --color=always --highlight-line {2} {1}'
}

# ============
# 現在のdir配下からfzfでファイルの中身を検索し、対象をvimで開く
# ------------
function vims() {
  local selected=$(_fsearch "$1") || return

  local file="${selected%%:*}"
  local rest="${selected#*:}"
  local line="${rest%%:*}"

  vim "+${line}" "$file"
}

# ============
# 現在のdir配下からfzfでファイルの中身を検索し、対象をエディターで開く
# ------------
function codes() {
  local selected=$(_fsearch "$1") || return

  local file="${selected%%:*}"
  local rest="${selected#*:}"
  local line="${rest%%:*}"

  code --goto "${file}:${line}"
}

gwc() {
  local dir
  dir=$(git worktree list | fzf | awk '{print $1}')
  [[ -n "$dir" ]] && cd "$dir"
}

export ENHANCD_DOT_ARG='...'

# 現在のディレクトリでpecoを使用してcdする
cd_by_peco_on_current_dir() {
  local selected_dir=$(fd . -t d -H | peco)
  if [ -n "$selected_dir" ]; then
    cd "$selected_dir"
    echo "cd $selected_dir"
    zle reset-prompt
  fi
}
zle -N cd_by_peco_on_current_dir

# ルートディレクトリからpecoを使用してcdする
cd_by_peco_on_root_dir() {
  local home_dir=$(realpath ~)
  local selected_dir=$(fd . "$home_dir" -t d -H | peco)
  if [ -n "$selected_dir" ]; then
    BUFFER="cd $selected_dir"
    zle accept-line
  fi
}
zle -N cd_by_peco_on_root_dir
bindkey '^P' cd_by_peco_on_root_dir

# 現在のディレクトリでpecoを使用してvimを開く
vim_by_peco_on_current_dir() {
  local selected_file=$(fd . -t f -H | peco)
  if [ -n "$selected_file" ]; then
    vim "$selected_file"
    echo "vim $selected_file"
    zle reset-prompt
  fi
}
zle -N vim_by_peco_on_current_dir

# ルートディレクトリからpecoを使用してvimを開く
vim_by_peco_on_root_dir() {
  local home_dir=$(realpath ~)
  local selected_file=$(fd . "$home_dir" -t f -H | peco)
  if [ -n "$selected_file" ]; then
    vim "$selected_file"
    echo "vim $selected_file"
    zle reset-prompt
  fi
}
zle -N vim_by_peco_on_root_dir
